CREATE DATABASE IF NOT EXISTS `starwars` DEFAULT CHARACTER SET utf8;

CREATE USER 'chibuzo'@'%' IDENTIFIED BY 'untold';

GRANT INSERT, CREATE, ALTER, UPDATE, SELECT, REFERENCES on starwars.*
TO 'chibuzo'@'%' IDENTIFIED BY 'untold'
WITH GRANT OPTION;

FLUSH PRIVILEGES;
